woowacourse-teams/2023-shook

backend/src/main/java/shook/shook/part/domain/Part.java
backend/src/main/java/shook/shook/part/domain/PartLength.java
backend/src/main/java/shook/shook/song/domain/Length.java
backend/src/main/java/shook/shook/song/domain/Song.java
backend/src/main/java/shook/shook/vote/domain/Vote.java

Feat/#27: Song, Vote 도메인 생성

---

.github/CODEOWNERS

PR 등록 시 자동으로 리뷰어를 등록하는 기능을 추가한다.
closes #54

[FEAT] PR 등록 시 자동으로 리뷰어를 등록하는 기능 추가

---

.github/workflows/backend-ci.yml

config: CI 트리거 추가

---

backend/src/main/resources/data.sql
backend/src/main/resources/schema.sql

DB 스키마 작성 및 개발 환경 더미 데이터 스크립트 작성
closed #28 
closed #71

Feat/#71: DB 스키마 작성 및 개발 환경 더미 데이터 스크립트 작성

---

.github/workflows/backend-ci.yml

Config: 워크 플로우 수동 동작 트리거 추가

---

frontend/src/components/IntervalInput/IntervalInput.stories.tsx
frontend/src/components/IntervalInput/IntervalInput.style.ts
frontend/src/components/IntervalInput/IntervalInput.test.tsx
frontend/src/components/IntervalInput/IntervalInput.tsx
frontend/src/components/IntervalInput/IntervalInput.type.ts
frontend/src/components/IntervalInput/constants/errorMessage.ts
frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
frontend/src/components/IntervalInput/index.ts
frontend/src/utils/convertTime.test.ts
frontend/src/utils/convertTime.ts
frontend/src/utils/validateTime.test.ts
frontend/src/utils/validateTime.ts

- input 4개 구현했습니다.
- 시작 구간 입력 시에 자동으로 끝이 입력됩니다.
- interval (5초 / 10초/ 15초)를 정할 수 있기 때문에, 끝점은 입력이 불가능하도록 하였습니다.
- 사용자가 옳은 입력을 할 수 있도록 change, blur, focus 이벤트를 이용하여 에러 메세지를 띄워줍니다.
사진
- 컴포넌트를 더 분리할 필요가 있는 지 확인해주세요.
- 추가로 할 테스트가 있는 지, 필요 없는 테스트는 있는 지 확인해주세요.
- 사용자에게 더 좋은 사용 경험을 위해 개선할 점이 있으면 알려주세요.
close #58

Feat/#58 IntervalInput 컴포넌트 (킬링파트 등록 시간 input) 구현

---

frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.stories.tsx
frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.style.tsx
frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.tsx
frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.type.ts
frontend/src/components/KillingPartToggleGroup/constants.ts
frontend/src/components/KillingPartToggleGroup/index.tsx

킬링파트 5초, 10초, 15초 구간을 선택하는 토글 버튼 그룹.
한 번에 하나의 버튼만 활성화되는 토글 버튼 그룹이다.
- 변수명이나 가독성이 괜찮은가요?
- 그룹에서 하나의 버튼만 활성화 되어야 하는데 이것을 어떻게 테스트 하면 좋을까요?
close #60

Feat/#60 킬링파트 구간을 선택하는 토글버튼그룹 구현

---

frontend/src/components/Modal/Modal.stories.tsx
frontend/src/components/Modal/Modal.style.ts
frontend/src/components/Modal/Modal.test.tsx
frontend/src/components/Modal/Modal.tsx
frontend/src/components/Modal/hooks/useModal.test.ts
frontend/src/components/Modal/hooks/useModal.ts
frontend/src/components/Modal/index.ts
frontend/src/pages/SongDetailPage.style.ts
frontend/src/pages/SongDetailPage.tsx

- useModal 훅을 구현함
- isOpen, openModal, closeModal 제공
- 모달 컴포넌트를 구현함
- 백드롭을 클릭하면 모달이 닫힘
- esc를 누르면 모달이 닫힘
SongDetailPage에 등록 모달 스타일도 구현하여 놓았음
close #68

Feat/#68 모달 컴포넌트를 구현한다

---

backend/build.gradle
backend/src/main/java/shook/shook/part/application/PartService.java
backend/src/main/java/shook/shook/part/application/dto/PartRegisterRequest.java
backend/src/main/java/shook/shook/part/application/dto/PartRegisterResponse.java
backend/src/main/java/shook/shook/part/domain/Part.java
backend/src/main/java/shook/shook/part/ui/PartController.java
backend/src/main/java/shook/shook/song/application/SongService.java
backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
backend/src/main/java/shook/shook/song/application/dto/KillingPartsResponse.java
backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
backend/src/main/java/shook/shook/song/domain/Parts.java
backend/src/main/java/shook/shook/song/domain/Song.java
backend/src/main/java/shook/shook/song/ui/SongController.java
backend/src/test/java/shook/shook/part/application/PartServiceTest.java
backend/src/test/java/shook/shook/part/domain/PartTest.java
backend/src/test/java/shook/shook/part/ui/PartControllerTest.java
backend/src/test/java/shook/shook/song/application/SongServiceTest.java
backend/src/test/java/shook/shook/song/domain/PartsTest.java
backend/src/test/java/shook/shook/song/ui/SongControllerTest.java

파트 등록, 노래 정보 조회 API 구현
closed #87

Feat/#87: 파트 등록, 노래 정보 조회 API 구현

---

.gitmodules
backend/src/main/resources/application.yml

Feat/#90 백엔드 서브모듈 적용

---

frontend/package-lock.json
frontend/package.json
frontend/src/types/youtube.d.ts

- `"@types/youtube": "^0.0.47"` 제거
- Youtube Iframe 타입 직접 정의
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/youtube/index.d.ts
close #114

Feat/#114 유튜브 iframe api 타입 정의(YT)

---

frontend/.eslintrc.js
frontend/package.json
frontend/webpack.dev.js

- webpack ReactRefreshWebpackPlugin overlay 설정
- eslint react version 'detect' 설정
- eslint 및 jest 실행 스크립트 추가
https://github.com/jsx-eslint/eslint-plugin-react#configuration
close #109

Feat/#109 환경설정 수정 및 추가

---

backend/src/main/resources/application.yml

개발 환경과 배포 환경의 yml 을 분리했다.
빠르게 반영해주세요
closes #98

Feat/#98 개발 환경, 배포 환경 yml 분리

---

.github/workflows/frontend-ci.yml

PR 생성시 github actions로 프론트엔드의 테스트(lint, test, build)를 실행한다.
[프론트엔드 CI wiki](https://github.com/woowacourse-teams/2023-shook/wiki/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C-CI)
close #123

Feat/#123 프론트엔드 테스트 CI (lint, test, build)

---

.github/workflows/frontend-ci.yml

프론트엔드 ci에 패키지를 설치하는 step이 누락되어 수정
close #136

Fix/#136 npm ci 실행 step 추가

---

.github/workflows/frontend-ci.yml

working directory 작성 및 if 절 순서 변경
close #136

Fix/#136 working directory 작성 및 if 절 순서 변경

---

.github/workflows/backend-ci.yml
.github/workflows/frontend-ci.yml

- paths 속성 삭제
- 프론트엔드 node-version을 matrix strategy가 아닌 env 환경 변수로 선언
이슈 참고 - #141
close #141

Fix/#141 폴더 상관없이 항상 CI를 실행하도록 변경

---

.github/workflows/backend-cd.yml
.github/workflows/backend-dev-cd.yml

Github Self-hosted Runner 를 사용한 백엔드 CD 설정 추가
closes #167

Feat/#167: 백엔드 CD 설정 추가

---

.github/workflows/backend-dev-cd.yml

Feat/#167 백엔드 CD pwd 로깅 추가

---

.github/workflows/backend-dev-cd.yml

입력 받은 브랜치 CD 실행하도록 변경
closes #167

Feat/#167 입력 받은 브랜치 CD 실행하도록 변경

---

.github/workflows/backend-dev-cd.yml

Feat/#167 실행 권한 root 로 지정

---

.github/workflows/backend-dev-cd.yml

Feat/#167 sudo 권한 삭제

---

backend/src/main/resources/application.yml

profile 오류로 인한 application.yml 수정
- 로컬에서는 local 프로파일로 진행
- 실 배포에서는 명령어에서 직접 프로파일 지정

Hotfix: profile 오류로 인한 application.yml 수정

---

backend/build.gradle

swagger 의존성 추가 ( 간단한 버전 )
#162

Feat/#162 swagger 의존성 추가

---

backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java

Hotfix: KillingPartResponse 에 id 추가

---

backend/src/main/java/shook/shook/song/application/dto/HighVotedSongResponse.java
backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
backend/src/main/java/shook/shook/song/domain/AlbumCoverUrl.java
backend/src/main/java/shook/shook/song/domain/Song.java
backend/src/main/resources/data.sql
backend/src/main/resources/schema.sql
backend/src/test/java/shook/shook/song/domain/AlbumCoverUrlTest.java
backend/src/test/resources/test.sql

SongResponse 에 albumCoverUrl 추가

Hotfix: SongResponse 에 albumCoverUrl 추가

---

backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java

SongResponse의 KillingPartResponse의 id를 part id 로 수정

Hotfix: SongResponse KillingPart id 수정

---

frontend/src/components/VoteInterface/VoteInterface.tsx
frontend/src/mocks/fixtures/songs.json
frontend/src/mocks/handlers/songsHandlers.ts

- 이미 만들어진 유틸에 대한 원 코드 삭제 및 적용
- api명세와 맞지 않는 msw 핸들러 수정
- 킬링파트 등록 POST 요청에 대한 핸들러 추가
- 코드 내 console.log 구문 삭제
간단한 리팩터링 및 msw 관련 작업입니다~
작은 단위의 수정이고, 로직 수정은 없으니 빠르게 훑어주세요~ㅎㅎ
close #204

Refactor/#204 컴포넌트 중복 코드 삭제 및 msw 핸들러 추가 및 수정

---

frontend/src/features/comments/components/CommentList.tsx
frontend/src/pages/MainPage.tsx

댓글 입력시 양쪽 공백 제거 (uncontrolled로 변경)
ROUTE_PATH 미변경사항 수정
#161 - ROUTE_PATH 미변경된 부분이 하나 있어서 수정했습니다. 
close #208 
close #211

Fix/#208 댓글 입력시 양쪽 공백 제거

---

.github/workflows/backend-prod-cd.yml
.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml

백엔드 prod, dev cd 작성
프론트엔드 prod, dev cd 작성

Refactor/#265: 백엔드 CD 수정, 프론트엔드 CD 추가

---

.github/workflows/backend-prod-cd.yml
.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml
backend/src/main/resources/schema.sql

dev 프로파일 분리, frontend-develop-cd 수정, ddl 수정

Refactor/#265: dev 프로파일 분리, frontend-develop-cd 수정, ddl 수정

---

.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml

Fix: cd yml 경로 수정

---

.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml

Hotfix: frontend build ubuntu 유저로 진행

---

backend/src/main/resources/logback/appender/slack-appender.xml

Hotfix: dev, prod 슬랙 알림 채널 분리

---

backend/src/main/java/shook/shook/song/domain/Song.java
backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartComment.java
backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
backend/src/main/java/shook/shook/voting_song/domain/Vote.java
backend/src/main/java/shook/shook/voting_song/domain/VotingSong.java
backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepositoryTest.java
backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepositoryTest.java
backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java

MILLIS -> MICROS (소수점 아래 6자리) 수정
closes #231

Refactor/#231 MILLIS -> MICROS (소수점 아래 6자리) 수정

---

backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
backend/src/test/java/shook/shook/auth/application/TokenProviderTest.java
backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
backend/src/test/java/shook/shook/auth/ui/AuthContextTest.java
backend/src/test/java/shook/shook/auth/ui/CookieProviderTest.java
backend/src/test/java/shook/shook/auth/ui/interceptor/PathMethodTest.java

로그인과 관련된 테스트 수정 및 추가
로그인과 관련된 테스트를 수정하고 추가하였습니다. 토큰을 재발급하는 과정에서 예외사항 테스트를 추가했습니다.
- close #304

TEST/#304 로그인과 관련된 테스트 수정 및 추가

---

backend/src/main/java/shook/shook/auth/ui/CookieProvider.java
backend/src/test/java/shook/shook/auth/ui/AuthControllerTest.java

쿠키 path 설정 수정했습니다.
없습니다.
- close #305

REFACTOR/#305 쿠키 path 설정 수정

---

backend/src/main/resources/dev/data.sql

개발 서버 초기 더미데이터를 추가한다.
없습니다.
- close #311

Data/#311 개발 서버 초기 더미데이터 추가

---

frontend/src/shared/components/Layout/AuthLayout.tsx
frontend/src/shared/components/Layout/Header.tsx

fix: MyPage 라우터 및 불필요한 memberId 정리

---

frontend/src/pages/MyPage.tsx
frontend/src/shared/components/Layout/AuthLayout.tsx
frontend/src/shared/components/Layout/Header.tsx

Fix/#322 useFetch를 사용하여 token을 넣어 요청을 보냄

---

frontend/src/features/auth/components/LoginModal.tsx
frontend/src/features/songs/components/KillingPartTrack.tsx
frontend/src/features/songs/components/VoteInterface.tsx

- 비로그인시 좋아요 클릭시 로그인 모달 
- 로그인 모달 메세지에 다중 메세지 받도록 수정 
작업내용
참고사항
close #323

Feat/#323 좋아요 클릭 시 로그인 여부에 따라 다르게 작동하도록 수정

---

frontend/src/pages/MainPage.tsx

votingSongs 곡이 없을경우 안내메세지 추가
작업내용
close #336

refactor: votingSongs 곡이 없을경우 안내메세지

---

backend/src/main/java/shook/shook/song/domain/KillingParts.java
backend/src/test/java/shook/shook/song/application/SongServiceTest.java
backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartsTest.java

노래 안의 킬링파트 조회 시, 좋아요 순으로 정렬 ( 좋아요 수가 같을 시 시작 시간 순으로 정렬 )
closes #340

Refactor/#340: 노래 안의 킬링파트 조회 시, 좋아요 순 - 시작 시간 순으로 조회

---

backend/src/main/java/shook/shook/globalexception/CustomException.java
backend/src/main/java/shook/shook/globalexception/GlobalExceptionHandler.java

오류 로깅 시 메세지와 에러 코드 포함
closes #331

Refactor/#331 오류 로깅 시 메세지와 에러 코드 포함

---

frontend/src/pages/PartCollectingPage.tsx

design: 수집페이지에서 텍스트가 긴 경우 ellipsis 적용

---

frontend/src/features/comments/components/CommentList.tsx
frontend/src/features/songs/components/KillingPartTrack.tsx
frontend/src/features/songs/components/SongDetailItem.tsx
frontend/src/features/songs/components/VoteInterface.tsx
frontend/src/features/youtube/components/Youtube.tsx
frontend/src/pages/SongDetailListPage.tsx
frontend/src/shared/components/Avatar.tsx
frontend/src/shared/components/Layout/Header.tsx
frontend/src/shared/components/Layout/Layout.tsx
frontend/src/shared/styles/GlobalStyles.ts
frontend/src/shared/styles/theme.ts

태블릿, xxs(380px 이하)   break point 까지 스와이프 적용
xxs 사이즈 적용하여 다 줄였습니다.
스크롤 마진 제거했습니다.
close #342

Fix/#342 420px(모바일 break point) 외의 사이즈에서 스와이프가 작동하지 않는 오류

---

frontend/src/pages/MainPage.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/PartCollectingPage.tsx

반응형 디자인 핫픽스입니다.
참고사항
close #351

fix: 디자인 핫픽스

---

frontend/.storybook/main.ts
frontend/.storybook/preview.tsx
frontend/package-lock.json
frontend/package.json

`@storybook/addon-styling` 애드온을 삭제하였습니다.
`@storybook/addon-styling`이 deprecated 되어 마이그레이션을 진행하려고 하였으나,
필요없는 애드온이라는 판단으로 **제거하게 되었습니다.**
#357 에 더 자세한 내용이 담겨있습니다.
close #357

Refactor/#357 @storybook/addon-styling 애드온 삭제

---

frontend/public/index.html

네트워크 탭에 id가 모두 노출되는 것으로 보아 굳이 환경변수로 등록할 필요가 없다고 생각해서 id를 그대로 index.html에 넣었습니다.
close #412

Feat/#412 사용자 분석을 위해 ga id 태그를 추가한다.

---

frontend/src/features/songs/components/SongItemList.tsx
frontend/src/features/songs/components/Thumbnail.tsx

fix: 이미지 사이즈 조정

---

backend/src/main/java/shook/shook/song/application/InMemorySongsScheduler.java

- 노래 캐싱 시 시간 확인을 위한 로그 추가
- 운영, 개발서버 스케줄러 동작 시간 스냅샷 최신화

Hotfix: 노래 캐싱 로그 추가 및 스냅샷 최신화

---

frontend/src/features/songs/components/CarouselItem.tsx
frontend/src/features/songs/components/VoteInterface.tsx
frontend/src/router.tsx
frontend/src/shared/styles/GlobalStyles.ts

- 킬링파트 등록 로그인 확인
기존: 킬링파트를 등록하려 할 때 로그인을 확인한다.
변경: 캐러셀을 클릭했을 때 로그인을 확인한다.
- 킬링파트 등록 시 모달에서 닉네임이 보이도록 추가한다.
- 킬링파트 등록 페이지에 ‘같은 파트에 대한 여러 번의 등록은 한 번의 등록으로 처리된다’ 문구를 표시한다.
close #463 
close #468

Refactor/#463, #468 캐러셀을 클릭했을 때 로그인이 안 된 경우 로그인 필요하다고 띄워준다

---

frontend/src/features/songs/components/KillingPartTrack.tsx
frontend/src/features/songs/components/SongDetailItem.tsx
frontend/src/features/youtube/components/Youtube.tsx
frontend/src/pages/PartCollectingPage.tsx

~~d0fffbb2b0d0d075f73c784e8db8d915d3ad942e - 이 커밋에 기록한 사항인데, Youtube 컴포넌트의 [createPlayerOnObserve](https://github.com/woowacourse-teams/2023-shook/blob/main/frontend/src/features/youtube/components/Youtube.tsx#L17)가 페이지를 빠져나갈때 컴포넌트 갯수만큼 실행됩니다.
처음에 해당 함수와 함께 url을 바꾸는 것으로 진행하다가 알게된 사실인데 원인은 분석하지 못했습니다.~~ - [모든 조건에서 실행하고 있었음](https://github.com/woowacourse-teams/2023-shook/pull/485/commits/a0955f4dc35b6bdd878c761a0c9378ae2c2f2cee#diff-f23b7ff86f848b4c744cd4be57b2f0b99d51f1fef78bf9a43f852b5ab6b3eba1L39)
이후 Youtube 컴포넌트가 PartCollectingPage에서도 사용됨을 인식하고 SongDetailItem에서 div 태그를 하나 만들어서 거기에 ref를 주어서 구현하였습니다. (https://github.com/woowacourse-teams/2023-shook/commit/16c1219ae20dfe6a125d34089674458468 …

Feat/#472 스와이프시 url이 변경되도록 한다.

---

backend/src/main/resources/schema.sql

config: schema에서 legacy_length 열 삭제

---

backend/build.gradle
backend/src/main/java/shook/shook/status/ProfileCheckController.java
backend/src/main/java/shook/shook/status/response/ProfileResponse.java
backend/src/main/java/shook/shook/status/response/ReservedProfiles.java

무중단 배포를 위한 Actuator 추가, Profile API 생성
- 프로파일 prod1, prod2 를 생성
- close #514

Feat/#514 무중단 배포를 위한 Actuator 추가, Profile API 생성

---

backend/src/main/java/shook/shook/auth/config/AuthConfig.java

hotfix: 메인 페이지 조회 시 토큰 받지 않도록 수정

---

backend/src/main/resources/dev/data.sql
backend/src/main/resources/dev/schema.sql

반영되지 않았던 member_part 테이블, length 타입 변경 내용 포함했습니다.

hotfix: dev schema 변경된 내용 반영

---

backend/src/main/resources/schema.sql

잘못 변경된 prod schema 롤백 진행했습니다.

hotfix: prod schema 롤백

---

backend/src/main/resources/dev/schema.sql

config: dev schema 동기화

---

frontend/src/features/songs/components/SongDetailItem.tsx

design: 듣기 페이지 가운데 정렬
