frontend/src/apis/index.ts
frontend/src/apis/killingPart.ts
frontend/src/apis/song.ts
frontend/src/hooks/@common/useFetch.ts
frontend/src/hooks/@common/useMutation.ts
frontend/src/hooks/killingPart.ts
frontend/src/hooks/song.ts
frontend/src/types/killingPart.ts
frontend/src/types/song.ts

- fetch 추상화 유틸 구현
- api 로직 구현
- 킬링파트 등록 post
- 노래상세정보 get
- fetch 추상화 custom hook 구현
- useFetch(get)
- useMutation(post, patch, delete등 )
- 컴포넌트에서 사용할 수 있는 개별 custom hook 구현
- usePostKillingPart
- useGetSongDetail
```
[fetch 유틸] --> [각 fetch함수] --> [useFetch / useMutaion hook] --> [use{METHOD}{DOMAIN} 형식의 hook] 
```
위 순서대로 단계별로 추상화 되어진 api flow입니다.
**fetch 유틸** : 각 `fetch함수`에서 사용하는 `fetch API`에서 공통되는 부분을 추상화한 유틸입니다.  
**useFetch / useMutaion** : `사용처(컴포넌트)`에서 필요한 통신 관련 공통 state(data, loading, error)를 제공하는 hook입니다.
앞으로 추가될 수많은 api 로직을 생각하여 각 로직을 `비슷한 레벨`로 관리할 수 있도록 신경써봤습니다.
프로젝트 내, 첫 api 로직이라 기준을 잘세우려고 노력했어요.
피드백 많이 부탁드립니다!
다들 화이팅입니다!
close #95

Feat/#95 킬링파트 등록 & 노래 상세 정보 API 로직을 구현

---

frontend/package.json
frontend/webpack.common.js
frontend/webpack.dev.js
frontend/webpack.prod.js

**cross-env 패키지 설치 없이도** 해결할 수 있는 방안이 있어 **아래와 같이 해결했습니다.**
1. script에서 주입하던 **NODE_ENV 환경변수 삭제**
2. webpack.common.js 파일에서 분기로 처리하던 dotenv path 관련 로직 `삭제` 및 `각 환경 별 설정파일로 이동`
- dev 환경 확인
- prod 환경 확인
프로젝트 내부에서 사용할 각 환경별 변수를 의논하여 정하면 될듯합니다.
현재는 `BASE_URL` 만 사용되고 있긴 합니다~
close #154

Feat/#154 윈도우 환경변수 주입 오류 해결

---

frontend/src/components/Layout/Header.tsx
frontend/src/components/Layout/Layout.tsx

- Header에 `/`으로 가는 Link를 추가한다.
- LayoutContainer에 color를 white로 설정한다.
현재 layout의 배경이 어두운 색이므로 기본 color를 white로 설정하였습니다.
close #176

Feat/#176 Layout을 수정한다 (Header, layout color)

---

backend/src/main/java/shook/shook/auth/application/AuthService.java
backend/src/main/java/shook/shook/auth/application/TokenProvider.java
backend/src/main/java/shook/shook/auth/ui/interceptor/TokenInterceptor.java
backend/src/main/java/shook/shook/member/application/MemberService.java
backend/src/main/java/shook/shook/member/domain/repository/MemberRepository.java
backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
backend/src/test/java/shook/shook/auth/application/TokenProviderTest.java
backend/src/test/java/shook/shook/auth/ui/TokenControllerTest.java
backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
backend/src/test/java/shook/shook/song/ui/KillingPartLikeControllerTest.java

토큰을 생성할 때 nickname추가하여 생성하도록 수정하였습니다.
- memberserivce의 register에서 email에서 nickname을 파싱하는 과정이 포함되어 있는데 이는 아직 소셜 로그인만 존재하여 따로 분리하지 않았습니다. 나중에서 다른 소셜 로그인이나 일반 로그인이 생기면 그 때 분리하면 좋을 것 같습니다.
- close #283

REFACTOR/#283 토큰을 생성하는 방식 수정

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

release drafter를 적용하여 다음 release까지 changelog들이 draft로 쌓이도록 적용하였습니다.
github action을 사용하였으며 main에 merge(push)될때 적용됩니다.
https://github.com/release-drafter/release-drafter
draft이므로 우리가 publish 해주어야 합니다.
- 좌측 사진에서 publish할 때 태그를 버저닝 해주어야 합니다.
- 우측 사진에서 기준 커밋을 정합니다.
close #287

Feat/#287 release drafter를 적용한다.

---

backend/src/main/java/shook/shook/song/application/SongService.java
backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
backend/src/main/resources/application-test.yml
backend/src/test/java/shook/shook/song/application/SongServiceTest.java
backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
backend/src/test/java/shook/shook/song/ui/SongControllerTest.java

이전 노래 조회 쿼리를 수정한다.
기존의 이전 노래 조회 쿼리는 첫 페이지의 결과를 리턴했는데, 마지막 페이지의 결과를 리턴하는 것이 옳은 작동 방식이었습니다.
그래서 노래 조회 쿼리를 좋아요 순 ASC, id 순 ASC 로 정렬하도록 변경했습니다.
closes #293

Hotfix/#293 이전 노래 조회 쿼리 수정

---

backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongSwipeResponse.java
backend/src/test/java/shook/shook/voting_song/application/VotingSongServiceTest.java
backend/src/test/java/shook/shook/voting_song/ui/VotingSongControllerTest.java

VotingSongSwipeResponse 필드 이름을 수정한다.
전체적으로 before -> prev, after -> next 로 변경한다.
closes #299

Hotfix/#299 VotingSongSwipeResponse 필드 이름을 수정한다

---

backend/src/main/resources/dev/schema.sql
backend/src/main/resources/schema.sql
backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
backend/src/test/resources/killingpart/initialize_killing_part_song.sql
backend/src/test/resources/schema-test.sql

killing_part like_count 디폴트값 추가
- 운영 서버의 sql은 alter table 명령을 추가했습니다. -> 운영 서버에 반영되었습니다.
- 그 외의 스크립트는 모두 테이블 생성 DDL 자체를 수정했습니다. 
참고사항
(close) #이슈번호

Hotfix: killing_part like_count 디폴트값 추가

---

frontend/src/features/songs/components/KillingPartInterface.tsx
frontend/src/features/youtube/components/Youtube.tsx

스와이프 페이지 이동 시 기존 재생 노래 멈춤 기능을 구현한다. 
인터섹션 옵저버로 화면 절반 이상 넘어가면 노래 멈추도록 구현했습니다!
close #337

Feat/#337 스와이프 페이지 이동 시 기존 재생 노래 멈춤 기능을 구현한다. 

---

frontend/src/features/songs/hooks/useKillingPartLikes.ts

킬링파트 좋아요를 누른 뒤 새로고침할 경우 좋아요 개수가 하나 더해져 있는 버그를 수정함.
close #335

fix: like 개수 상태를 두어 새로고침 뒤에 정합성 유지

---

backend/src/main/java/shook/shook/auth/config/AuthConfig.java
backend/src/main/java/shook/shook/auth/exception/AuthorizationException.java
backend/src/main/java/shook/shook/globalexception/ErrorCode.java
backend/src/main/java/shook/shook/globalexception/GlobalExceptionHandler.java
backend/src/main/java/shook/shook/member/application/MemberService.java
backend/src/main/java/shook/shook/member/ui/MemberController.java
backend/src/main/java/shook/shook/member/ui/openapi/MemberApi.java
backend/src/main/resources/dev/data.sql
backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java
backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
backend/src/test/java/shook/shook/member/ui/MemberControllerTest.java

회원이 **자발적으로** 탈퇴할 때, 회원을 삭제하는 기능을 구현했습니다.
- 특정 id의 member를 삭제한다는 의미이기 때문에 URL을 `members/{member_id}` 로 설정했습니다.
- 아코에게서는 현장에서 코드 리뷰를 받았습니다 ^^
closes #371
#382

Feat/#371: 회원 탈퇴 기능 구현

---

frontend/src/pages/SongDetailListPage.tsx
frontend/src/shared/hooks/useExtraFetch.ts
frontend/src/shared/utils/createObserver.ts

1ref + 1effect 로 옵져버 실행시키는 구조입니다.
첫 노래 상세정보 API 응답 **이후에** 옵져버를 실행시켜야 하는등 제약 조건이 조금 있어서 로직이 많아 졌어요
관련해서 api가 수정되면 좋을 것 같아서 건의해둔 상태입니다!
현재 관련해서 API 수정 건의가 진행중입니다~!
개선되면 로직도 가벼워지고, DOM 구조 역시 더 간단해질 것 같아요.
**as is :** extraPrev, prev, next, extraNext 총 4개의 데이터 배엘에 map() 
**to be :**  prev, next 총 2개의 데이터 배열에 map()
원래 사용자에게 제공되야 했던 기능이었어서 
#333 bug fix브랜치 기준으로 prod 배포 미리 나갔습니다!
close #333

Fix/#333 노래 상세정보 추가 fetch를 위한 인터섹션 옵저버 오류 수정

---

backend/src/main/java/shook/shook/member/domain/Member.java
backend/src/main/resources/dev/schema.sql
backend/src/main/resources/schema.sql
backend/src/test/java/shook/shook/member/domain/repository/MemberRepositoryTest.java
backend/src/test/resources/killingpart/initialize_killing_part_song.sql
backend/src/test/resources/schema-test.sql

Member 엔티티에 created_at 을 추가한다.
바뀐 건 크게 없습니다.
잠실 가자마자 dev DB 배포해보고, 운영 DB 반영하겠습니다. 
운영 DB 반영하면서 기존의 데이터들은 그때 시점 now() 로 반영할 예정입니다.
close #380

Feat/#380 Member 엔티티에 created_at 을 추가한다.

---

backend/build.gradle
backend/src/main/java/shook/shook/globalexception/ErrorCode.java
backend/src/main/java/shook/shook/song/application/SongDataExcelReader.java
backend/src/main/java/shook/shook/song/application/SongService.java
backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
backend/src/main/java/shook/shook/song/exception/SongDataFileReadException.java
backend/src/main/java/shook/shook/song/exception/SongException.java
backend/src/main/java/shook/shook/song/ui/AdminSongController.java
backend/src/main/resources/application-test.yml
backend/src/main/resources/application.yml
backend/src/test/java/shook/shook/song/application/SongServiceTest.java
backend/src/test/java/shook/shook/song/ui/AdminSongControllerTest.java

기본 한곡 추가 api 에 노래 중복 검증 추가
불필요한 괄호 삭제
- 엑셀 파일을 통해 노래 데이터 등록 API 구현
- 특정 포맷에 대해서는 다른 곳에서 공유하겠습니다. 
- 기본 한곡 추가 api 에 노래 중복 검증 추가
- 불필요한 괄호 삭제
참고사항
이번 이벤트까지 사용하기 위해 기한을 맞추려고 테스트코드는 우선 생략하였습니다.
close #388

Feat#388: 엑셀 파일을 통해 노래 데이터 등록 API 구현

---

frontend/src/features/auth/components/LoginModal.tsx
frontend/src/features/comments/components/CommentForm.tsx

- 비로그인 상태로 댓글 작성 시도 시 로그인 권유 모달이 표시되도록 변경
- 중복된 삼항연산자 제거
코드에 간단한 설명 코멘트 적어둘게요~!
참고해 주세요~
본 PR은 https://github.com/woowacourse-teams/2023-shook/pull/392 PR 먼저 merge 후 충돌 해결하여 merge할 예정입니다.
충돌 예상 코드는 LoginModal 내부 네비게이션 코드입니다~
close #400

Refactor/#400 비로그인 상태로 댓글 작성 시도 시 로그인 권유 모달이 표시되도록 변경

---

frontend/src/features/youtube/components/Youtube.tsx
frontend/src/pages/SongDetailListPage.tsx

[youtube player 생성 시점을 intersection observer로 제어 하도록 개선](https://github.com/woowacourse-teams/2023-shook/commit/5e4a5a68513f308221c42ec96085ef511745359a)
[paint 전 단계에 스크롤 이동 하도록 개선](https://github.com/woowacourse-teams/2023-shook/commit/ff8f27f2dc806275146ce602d36359f5430a0ea9)
스크립트 로드를 제어하여 1개의 player를 구성하는데 필요한 3개의 js파일을 로드하면서,
이후 요청에 대한 **캐시까지 적용되는 모습입니다.**
기존에는 21개의 player를 병렬적으로 한번에 로드했기 때문에, 
중복되는 스크립트임에도 각 요청시 캐시된 스크립트가 없어, **63개의 js파일을 불러오는 대참사가 발생했던 거죠.😅**
저희 모두에게 좋은 경험이 된 것 같네요.
커밋 메세지 바디에 상세 설명 적어놓았습니다.
callbackRef, observer ref 생성 이유, layoutEffect 사용 이유에 대한 설명이 더 필요하시면 바로 말해주세요~ 
대화로 설명 드리겠습니다~😀
close #408

Refactor/#408 SongDetailListPage의 Youtube Player 스크립트 로딩 성능 개선

---

backend/src/main/java/shook/shook/song/application/SongDataExcelReader.java
backend/src/main/java/shook/shook/song/application/dto/SongWithKillingPartsRegisterRequest.java
backend/src/main/java/shook/shook/song/domain/Genre.java
backend/src/main/java/shook/shook/song/domain/Song.java
backend/src/main/resources/dev/schema.sql
backend/src/main/resources/schema.sql
backend/src/test/java/shook/shook/song/application/SongServiceTest.java
backend/src/test/java/shook/shook/song/domain/GenreTest.java
backend/src/test/java/shook/shook/song/domain/SongTest.java
backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartTest.java
backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
backend/src/test/java/shook/shook/song/ui/AdminSongControllerTest.java
backend/src/test/resources/killingpart/initialize_killing_part_song.sql
backend/src/test/resources/schema-test.sql

Song 도메인에 Genre 필드 추가
- 우선은 장르 데이터가 없는 이전 노래들을 위해 Genre를 nullable 로 설정했습니다.
- 이 부분은 운영 서버 데이터의 노래들에 장르가 모두 추가되면 schema.sql 을 모두 nullable=false 로 설정하겠습니다.
closes #420

Feat/#420 Song 도메인에 Genre 필드 추가

---

backend/src/main/resources/dev/schema.sql
backend/src/main/resources/schema.sql
backend/src/test/resources/killingpart/initialize_killing_part_song.sql
backend/src/test/resources/schema-test.sql

Hotfix: genre schema 수정

---

backend/src/main/java/shook/shook/song/application/SongDataExcelReader.java

엑셀 노래 제목 데이터가 숫자로 구성된 상황을 처리한다.
- 해당 데이터 엑셀 입력 시, 제목셀을 `numericCell`로 인식하는 문제 발생
- DataFormatter로 문자열로 읽어오도록 수정

Hotfix: 엑셀 노래 제목 데이터가 숫자로 구성된 상황을 처리한다.

---

backend/build.gradle
backend/src/main/java/shook/shook/auth/application/AuthService.java
backend/src/main/java/shook/shook/auth/application/TokenPairScheduler.java
backend/src/main/java/shook/shook/auth/application/dto/ReissueAccessTokenResponse.java
backend/src/main/java/shook/shook/auth/exception/TokenException.java
backend/src/main/java/shook/shook/auth/repository/InMemoryTokenPairRepository.java
backend/src/main/java/shook/shook/auth/ui/AccessTokenReissueController.java
backend/src/main/java/shook/shook/auth/ui/openapi/AccessTokenReissueApi.java
backend/src/main/java/shook/shook/globalexception/ErrorCode.java
backend/src/main/resources/application-test.yml
backend/src/main/resources/application.yml
backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
backend/src/test/java/shook/shook/auth/application/TokenPairSchedulerTest.java
backend/src/test/java/shook/shook/auth/repository/InMemoryTokenPairRepositoryTest.java
backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java

- refreshToken과 accessToken을 concurrentHashMap으로 관리하도록 구성 (key는 refreshToken으로 value는 accessToken로 관리합니다.)
- 현재 스케줄러를 통해 InMemoryTokenPairRespository를 갱신하고 있습니다.
-  스케줄러로 관리를 했던 이유는 처음에는 요청 올 때 refreshToken의 유효성을 판단해서 제거를 하려고 했는데 실제로 refreshToken은 cookie로 관리가 되고 있기 때문에 기간이 지나면 refreshToken을 담은 요청이 오지 않아서 메모리에서 삭제되지 않고 계속 유지되는 문제가 있었습니다. 그래서 스케줄러로 관리하는 방식을 택했습니다.
- swagger를 다루어 본적이 없어서 swagger 설정을 올바르게 했는지 잘 모르겠습니다.
- 혹시 토큰 메모리를 스케줄러 외의 더 잘 관리할 수 있는 방안이 있으면 의견 부탁드랍나다.🙇‍♂️
- close #385

Feat/#385 토큰을 관리하는 방식 수정

---

frontend/src/pages/SongDetailListPage.tsx
frontend/src/shared/components/Modal/Modal.tsx

스와이프 코치마크의 백드랍을 클릭하여도 모달이 닫히지 않도록 수정하였습니다.
canCloseByBackDrop 속성을 추가하여 backdrop 클릭시 canCloseByBackDrop 여부를 확인하고 닫히도록 수정하였습니다.
#432 PR 참고
close #431

Hotfix: 스와이프 코치마크의 백드랍을 클릭하여도 모달이 닫히지 않도록 수정

---

frontend/src/shared/remotes/preCheckAccessToken.ts

- 이전 과정 
- 인증이 필요없는 요청 
- refresh 만료로 인해 토큰 갱신과정에서 401 발생
- error 발생 후 로그인하라는 모달 띄워준다.
문제는 인증이 필요한 요청임에도 로그인 모달을 띄워주고, 본 요청이 실행되지 않습니다. 이를 막기 위해 코드를 수정했습니다.
- 변경 이후
- 인증이 필요없는 요청
- refresh 만료로 인해 토큰 갱신과정에서 실패
- access token 삭제
- 본 요청 발생
close #445

Fix/#445 preCheckAccessToken 로직 변경

---

frontend/src/features/songs/components/CarouselItem.tsx
frontend/src/features/songs/components/CollectionCarousel.tsx
frontend/src/features/songs/components/Thumbnail.tsx
frontend/src/shared/remotes/preCheckAccessToken.ts

Refactor/#443 캐러셀 컴포넌트 및 썸네일 컴포넌트 리팩터링

---

frontend/src/features/songs/components/KillingPartTrack.tsx
frontend/src/pages/MyPage.tsx
frontend/src/shared/constants/GAEventName.ts
frontend/src/shared/googleAnalytics/sendGAEvent.ts
frontend/src/shared/types/ga.d.ts

- GA 이벤트 추가를 위한 유틸함수 추가
- 플레이 버튼, 좋아요,  공유, 프로필편집, 로그아웃, 
작업내용
- [ 노래 듣기 세부 페이지 ]Category: song_playing 
- 플레이
- 좋아요
- 공유
- [ 프로필 페이지 ] Category: profile
-  프로필편집
- 로그아웃
close #460

Feat/#460 GA 이벤트 추가

---

backend/src/main/java/shook/shook/voting_song/application/VotingSongPartService.java
backend/src/main/java/shook/shook/voting_song/domain/Vote.java
backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
backend/src/main/java/shook/shook/voting_song/domain/VotingSongParts.java
backend/src/main/java/shook/shook/voting_song/domain/repository/VoteRepository.java
backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongPartRepository.java
backend/src/main/java/shook/shook/voting_song/ui/VotingSongPartController.java
backend/src/main/java/shook/shook/voting_song/ui/openapi/VotingSongPartApi.java
backend/src/main/resources/dev/schema.sql
backend/src/main/resources/schema.sql
backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
backend/src/test/java/shook/shook/voting_song/application/VotingSongPartServiceTest.java
backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartTest.java
backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartsTest.java
backend/src/test/java/shook/shook/voting_song/domain/VotingSongTest.java
backend/src/test/java/shook/shook/voting_song/domain/repository/VoteRepositoryTest.java
backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
backend/src/test/java/shook/shook/voting_song/ui/VotingSongPartControllerTest.java
backend/src/test/resources/schema-test.sql

VotingSong -> VotingSongParts -> Member 로의 많은 N+1 쿼리가 예상되기에
```java
boolean existsByVotingSongAndMemberAndStartSecondAndLength(final VotingSong votingSong,
final Member member,
final int startSecond,
final PartLength length);
```
해당 메서드를 사용해서 확인했습니다.😊
추후에 해당 쿼리에 대한 분석과 인덱스 적용 여부에 대해서 파악해야 됩니다!!😁
멤버가 같은 파트를 등록했을 때는 200(OK), 아닌 경우에는 201(CREATED) 를 사용해서 클라이언트에게 전달하려 했으나 이 부분에 대해서 추후 프론트 팀원들과의 논의가 필요할 것 같습니다!!🫡
close #461

Refactor/#461 같은 멤버가 등록중인 노래에 같은 부분을 킬링파트로 등록시 추가 데이터를 저장하지 않는 기능 구현

---

frontend/src/pages/MyPage.tsx

좋아요한 킬링파트 공유 링크에 변경된 라우터 경로 적용
라우터 경로에 맞게 `/ALL` 을 붙여주었습니다. 
운영 서버에 에러가 나고 있는 상황이라 바로 머지 하려고 합니다.
해당 링크 공유 경로가 env 파일의 BASE_URL 기준으로 적용되어 있더라고요
이 부분을 replace 함수를 사용하여 'api' 부분만 제거하는식으로 사용되고 있는데 추가적인 환경변수를 만드는게 어떨까 싶네요
@cruelladevil 에게 
팀원 전체 밤샘 이슈로 미처 하지 못했던 리뷰를 남겨봅니다.
1. 해당 페이지 컴포넌트에 다른 하위 컴포넌트가 존재하더라고요 분리해 주시면 좋겠습니다.
2. 랜덤 노랫말 계산 로직이 jsx return문 내부에 있어서 다소 복잡한 감이 있는것 같아요 이 부분 분리되면 좋을 것 같아요.
3. like 불러오는 api 함수를 예전에 대화나눴던 대로 적당한 네이밍과 함께 features/SomeComponent/remote 하위에 함수로 분리해주면 감사하겠습니다~
4. 코난 작업 범위중에 위 3번 처럼 api 함수 분리 안된 부분이 있다면 같이 수정되면 좋을 것 같아요~
#452

Fix/#452 좋아요한 킬링파트 공유 링크에 변경된 라우터 경로 적용

---

frontend/src/pages/MyPage.tsx

- 마이페이지에서 좋아요한 노래 아이템 클릭시 노래 듣기로 이동
- 카테고리는 ALL입니다.
급하게 반영할 사항이라 merge 하겠습니다. 수정된 부분은 극히 적어요!
close #483

Hotfix/#483 마이페이지에서 좋아요한 노래 아이템 클릭시 노래 듣기로 이동

---

.github/workflows/frontend-ci.yml
.github/workflows/frontend-dev-cd.yml
.github/workflows/frontend-prod-cd.yml

frontend prod CD에 npm 캐시 추가하였습니다.
CI에도 CD와 동일한 캐시 name, key, restore-key를 갖도록 수정하였습니다.
close #518

Refactor/#518 frontend prod CD에 npm 캐시 추가

---

frontend/src/features/songs/components/KillingPartInterface.tsx
frontend/src/features/songs/components/KillingPartTrackList.tsx
frontend/src/features/songs/components/SongDetailItem.tsx

Refactor/#505 댓글 기능을 임시 중단하고 킬링파트 듣기 페이지의 디자인을 수정한다.

---

frontend/src/features/songs/components/SongDetailItem.tsx

모바일에서는 중앙 정렬시 잘 안보여서 sm 사이즈 이하로는 flex-start로 설정
참고사항
(close) #이슈번호

Hotfix#505 sm 이하 넓이에서는 컨테이너가 flex-start가 되도록 변경

---

frontend/src/features/songs/hooks/useExtraSongDetail.ts
frontend/src/features/songs/hooks/useSongDetailEntries.ts
frontend/src/mocks/handlers/songsHandlers.ts
frontend/src/pages/SongDetailListPage.tsx

- effect를 제거하고 callbackRef를 적용하였습니다~!
- SongDetailListPage 내의 로직을 커스텀 훅으로 분리하였습니다.
- useExtraSongDetail
- useSongDetailEntries
파일이 추가되어 변경사항이 많아보입니다만, 사실 원래있던 로직 분리만 한거라 변경사항은 딱 1개입니다
**effect를 제거하고 내부 로직을 callbackRef 함수로 이동시켰어요!**
이 개선 사항은 제가 몇 번 설명했던 부분이라 변경사항 쉽게 파악 가능하실거에요!
- **page 단위에 있던 로직을 hook으로 분리한거라** 어디에 둘지 조금 **애매**하긴했는데, **songs/hooks 하위로 위치시켰습니다.**
close #551

Refactor/#551 SongDetailListPage의 스와이프 추가 fetch 옵져버 로직에 callbackRef를 적용하여 로직 흐름을 개선한다.

---

frontend/practice.js
frontend/src/features/killingParts/components/RegisterPart.tsx
frontend/src/shared/components/ConfirmModal/ConfirmModal.stories.tsx
frontend/src/shared/components/ConfirmModal/ConfirmModal.tsx
frontend/src/shared/components/ConfirmModal/ConfirmModalProvider.tsx
frontend/src/shared/components/ConfirmModal/hooks/useConfirm.ts
frontend/src/shared/components/ConfirmModal/hooks/useConfirmContext.ts

전역에서 사용할 Confirm Modal을 구현하였습니다. 
- 스타일은 기존 모달과 같습니다.
- Confirm Modal 은 여러개를 띄울 일이 없기 때문에 전역에 두었습니다.
- `useConfirm` 을 사용하여 confirm 함수를 사용하시면 됩니다.
1. `useConfirm` 사용법
- 인자
- `title`, `content`, `denial`, `confirmation` 을 객체로 인자를 받습니다.
- `content` 타입은 ReactNode이며 나머지는 string만 받습니다.
- `denial`, `confirmation` 은 버튼의 이름을 뜻합니다. 기본값은 닫기와 확인입니다.
- 반환값
- `Promise<boolean>`을 반환합니다.
- useConfirm 사용처에서 확인/닫기 시에 어떤 일을 할 지 작성할 수 있습니다.
2. 스토리북을 이용해주세요.
**기존 코드에서 confirm 성격의 모달을 사용하는 곳에 아직 대체하지 않았습니다.** 해당 PR이 approve 받으면 변경 적용하는 작업을 별도의 PR로 하겠습니다. 이유는 리뷰 중에 해당 구현이 변경될 수 있기 때문입니다.
close #550

Feat/#550 Confirm Modal 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/features/comments/components/CommentForm.tsx
frontend/src/features/comments/components/CommentList.tsx
frontend/src/features/comments/queries/index.ts
frontend/src/features/comments/remotes/comments.ts
frontend/src/features/songs/hooks/useExtraSongDetail.ts
frontend/src/features/songs/hooks/useSongDetailEntries.ts
frontend/src/features/songs/queries/index.ts
frontend/src/index.tsx
frontend/src/mocks/handlers/songsHandlers.ts
frontend/src/pages/SongDetailListPage.tsx

- useExtraFetch -> useInfiniteQuery 대체
- useFetch -> useQuery 대체
현재 스와이프 페이지 내에서 총 3개의 get 요청을 하고있는데요! 지금의 api 구조로는 2개의 useInfiniteQuery 사용이 불가피했습니다.
또한 페이지에 suspense 적용을 고려했지만, api 워터폴현상이 발생해서 적용하지 못했습니다
(추후 각 api별 컴포넌트 분리가 이뤄지거나, 혹은 api변경이 이루어져서 1개의 infiniteQuery로만 해결 가능해지면, Suspense적용이 가능할것 같습니다.)
useInfiniteQuery의 초기 fetch 시 사용할 pageNumber를 defaultPageParam으로 줄 수 있는데요!
사용자가 선택한 노래(currentSong)의 id를 위, 아래방향 useInfiniteQuery에 defaultPageParam으로 넘겨 해결했습니다.
(이 과정에서 prev, nextSongs 배열은 사용하지 않게 되었습니다.)
mutaion에 대한 onSuccess는 useMutaion 사용시, mutate 함수 사용시 적용 가능합니다.
이때 순서는 useMutation -> mutate 함수 순으로 실행됩니다.
때문에 query cache 무효화 관련 로직은 useMutation 사용처에 작성했고,
UI관련(토스트 띄우기, 컴포넌트 상태 초기화 등등)은 mutate 함수 사용처에서 작성했습니다.
close #558

Feat/#558 스와이프, 댓글 기능에 React-Query 적용

---

frontend/src/features/killingParts/components/RegisterPart.tsx
frontend/src/pages/EditProfilePage.tsx

EditProfilePage, RegisterPart에 대한 머지 컨플릭트 수정
close #563

Fix/#563 머지 컨플릭트 해결

---

frontend/src/router.tsx
frontend/src/shared/hooks/useOverlay/OverlayController.tsx
frontend/src/shared/hooks/useOverlay/OverlayProvider.tsx
frontend/src/shared/hooks/useOverlay/index.ts
frontend/src/shared/hooks/useOverlay/types.ts
frontend/src/shared/hooks/useOverlay/useOverlay.tsx

오버레이란 모달, 바텀싯처럼 별도의 UI 레이어에 띄우는 컴포넌트를 뜻합니다.
오버레이를 다루는 useOverlay훅을 구현하여 바텀싯, 모달 컴포넌트를 useOverlay 훅을 통해 오버레이에 띄울 수 있도록 합니다.
https://slash.page/ko/libraries/react/use-overlay/src/useOverlay.i18n
close #566

Feat/#566 overlay를 다룰 useOverlay 훅 구현

---

frontend/src/features/comments/components/CommentForm.tsx
frontend/src/features/comments/components/CommentList.tsx
frontend/src/features/comments/queries/index.ts
frontend/src/features/songs/hooks/useExtraSongDetail.ts
frontend/src/features/songs/hooks/useSongDetailEntries.ts
frontend/src/features/songs/queries/index.ts
frontend/src/shared/hooks/useMutation.ts

https://github.com/woowacourse-teams/2023-shook/issues/573
https://github.com/woowacourse-teams/2023-shook/issues/573
close #573

Refactor/#573 useQuery를 훅으로 감싸는 방식에서 queryOptions를 활용하는 방식으로 변경
